version: '3'
services:
  
  inewgent_proxy:
    image: nginx
    container_name: inewgent_proxy
    volumes:
      - ./nginx/conf.d/inewgent-my.conf:/etc/nginx/conf.d/inewgent-my.conf
      - ./nginx/conf.d/inewgent-api.conf:/etc/nginx/conf.d/inewgent-api.conf
      - ./nginx/conf.d/inewgent-www.conf:/etc/nginx/conf.d/inewgent-www.conf
    ports:
      - "80:80"
    networks:
      network-inewgent:
        
networks:
  network-inewgent:
    external: true
