version: '3'
services:
  
  inewgent_proxy:
    image: nginx
    container_name: inewgent_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      network-inewgent:
        
networks:
  network-inewgent:
    external: true
